{% set name = "protobuf_to_pydantic" %}
{% set version = "0.3.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/protobuf_to_pydantic-{{ version }}.tar.gz
  sha256: 6710a1ca858d1e7294564e04ce08ec6b06ee18960dcb13865c02cda3dfe2435e

build:
  entry_points:
    - protoc-gen-protobuf-to-pydantic = protobuf_to_pydantic.plugin.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
    - pip
  run:
    - python >={{ python_min }}
    - pydantic >=1.9.2,<3.0.0
    - protobuf >=3.20.3
    - mypy-protobuf >=3.2.0,<4.0.0
  run_constrained:
    - toml >=0.10.2,<0.11.0
    - lark >=1.1.2,<2.0.0

test:
  imports:
    - protobuf_to_pydantic
  commands:
    - pip check
    - protoc-gen-protobuf-to-pydantic --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/so1n/protobuf_to_pydantic
  summary: Generate the `pydantic.BaseModel` class (and the corresponding source code) with parameter verification function through the Protobuf file
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache

extra:
  recipe-maintainers:
    - dillonroach
    - timkpaine
